name: metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # every day at 06:00 UTC
  push:
    branches: [ main ]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: victorcarmo2003
          template: classic

          base: header
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          config_timezone: America/Sao_Paulo
